# Levantar el ambiente: docker-compose up
# Para reiniciar todo el ambiente: en
# este comando es para cuando hay bugs de conexion docker-compose down -v
version: '3.3'
services:
  mysql_db:
    container_name: mysql_<%= nombreAplicativo %>_dev
    image: mysql:<%= tagMysql %>
    restart: always
    environment:
      # Nombre de la base de datos
      MYSQL_DATABASE: 'test'
      # Usuario de la base de datos
      MYSQL_USER: 'manticore'
      # Password de la base de dato
      MYSQL_PASSWORD: '12345678'
      # Password del root
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '<%= puertoMysql %>:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-volume:/var/lib/mysql/<%= nombreAplicativo %>
  redis_db:
    container_name: redis_<%= nombreAplicativo %>_dev
    image: redis:<%= tagRedis %>
    restart: always
    ports:
      # <Port exposed> : < Redis Port running inside container>
      - '<%= puertoRedis %>:6379'
    expose:
      # Opens port 6379 on the container
      - '6379'
    volumes:
      - redis-volume:/data/redis/<%= nombreAplicativo %>
<% if(urlMongo !== ""){ %>  mongo_db:
    container_name: mongo_<%= nombreAplicativo %>_dev
    image: mongo:<%= tagMongo %>
    restart: always
    environment:
      # Usuario de la base de datos
      MONGO_INITDB_ROOT_USERNAME: 'manticore'
      # Password de la base de datos
      MONGO_INITDB_ROOT_PASSWORD: '12345678'
      # Nombre de la Base de datos
      MONGO_INITDB_DATABASE: 'test'
      # Root password
      MONGODB_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MONGODB Port running inside container>
      - '<%= puertoMongo %>:27017'
    expose:
      # Opens port 27017 on the container
      - '27017'
    volumes:
      - mongo-db-volume:/data/db/<%= nombreAplicativo %>
      - mongo-config-volume:/data/configdb/<%= nombreAplicativo %>
  <% } %>
# Names our volume
volumes:
  mysql-volume:
  redis-volume:
<% if(urlMongo !== ""){%>  mongo-config-volume:
  mongo-db-volume:
  <% }%>